### ISSUE TITLE
[CrashManager] Line number should not be present in MOZ_CRASH

### ISSUE THREAD

**Issue by nth10sd** [MozillaSecurity/FuzzManager#156]
The line number should not be present in the Short Signature if a MOZ_CRASH is hit.

ref ID: 151553

**Comment by nth10sd** [comment]
Spoke to @jruderman and @choller, and @choller mentioned to file this issue.

**Comment by choller** [comment]
I decided to fix this by looking for "Hit MOZ_CRASH" rather than "MOZ_CRASH".

We shouldn't actually extract the MOZ_CRASH line from GDB data because that makes the generated signature incompatible to other debug info sources like ASan or any other debugger not showing the source code line in that spot (or even GDB without source information).
