### ISSUE TITLE
Include ASan messages in the signature

### ISSUE THREAD

**Issue by tysmith** [MozillaSecurity/FuzzManager#179]

**Comment by choller** [comment]
So basically this boils down to having `getAssertion` return ASan messages as well (except for the standard SIGSEGV message). I don't like the idea that `getAssertion` returns more and more things that aren't actual assertions and I'm thinking about refactoring the whole code to have `getAssertion` really only return assertions (removing the `onlyProgramAssertions` as it's always implied then) and add a second method to get other abort messages and both methods will be called for crash signature generating.

However, some people are using the `getAssertion` interface already, since it's a public interface.

@jruderman I know you use this method, can you quickly explain how and where you use it? I don't want to break your code by this refactoring.
